apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackProvisionServer
metadata:
  name: openstack-provision-server 
  namespace: openstack 
spec:
  nodeSelector:
    node-role.kubernetes.io/master: ''
  baseImageUrl: http://172.16.96.218/image/rhel-9.2-x86_64-kvm.qcow2
  port: 8080
  # interface: enp8s0