apiVersion: v1
data:
  cloud_name.yaml: |-
    parameter_defaults:
      CloudDomain: ocp4.example.com
      CloudName: overcloud.ocp4.example.com
      CloudNameInternal: overcloud.internalapi.ocp4.example.com
      CloudNameStorage: overcloud.storage.ocp4.example.com
      CloudNameStorageManagement: overcloud.storagemgmt.ocp4.example.com
      CloudNameCtlplane: overcloud.ctlplane.ocp4.example.com
  network_environment.yaml: |-
    parameter_defaults:
      ComputeNetworkConfigTemplate: 'single_nic_vlans.j2'
  containers-prepare-parameters.yaml: |-
    parameter_defaults:
      ContainerImagePrepare:
      - push_destination: false
        set:
          ceph_alertmanager_image: ose-prometheus-alertmanager
          ceph_alertmanager_namespace: registry.redhat.io/openshift4
          ceph_alertmanager_tag: v4.6
          ceph_grafana_image: rhceph-6-dashboard-rhel9
          ceph_grafana_namespace: registry.redhat.io/rhceph
          ceph_grafana_tag: latest
          ceph_image: rhceph-6-rhel9
          ceph_namespace: registry.redhat.io/rhceph
          ceph_node_exporter_image: ose-prometheus-node-exporter
          ceph_node_exporter_namespace: registry.redhat.io/openshift4
          ceph_node_exporter_tag: v4.6
          ceph_prometheus_image: ose-prometheus
          ceph_prometheus_namespace: registry.redhat.io/openshift4
          ceph_prometheus_tag: v4.6
          ceph_tag: latest
          name_prefix: openstack-
          name_suffix: ''
          namespace: registry.redhat.io/rhosp-rhel9
          neutron_driver: ovn
          rhel_containers: false
          tag: '17.1'
        tag_from_label: '{version}-{release}'
      ContainerImageRegistryCredentials:
        registry.redhat.io:
          <USERNAME>: '<PASSWORD>'
      ContainerImageRegistryLogin: true
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: heat-env-config
  namespace: openstack
